### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by luis-stakeordie** [SecretFinance/SecretSwap#4]

**Comment by HowardBraham** [comment]
@luis-stakeordie Is this about the APR and ROI being rounded prematurely?  Or is it another rounding error?

I would personally like more significant figures in a few places and fewer significant figures in others.

**Comment by ESWood** [comment]
The Rounding Error is referencing an error commonly encountered on https://app.secretswap.io/earn

When providing or withdrawing LP, a user will hit 100% to either "Earn" or "Withdraw" to initiate the transaction. Rather than opening Keplr, the UI will stop with the spinning wheel on the button and hang indefinitely. The workaround for this is to remove the decimals from the amount, for instance, change 100.10219833414718 to 100. The UI will then open Keplr, process the transaction as normal and the user will have to perform a 2nd transaction to move the remainder "dust".

**Comment by 7Two1** [comment]
Fix [here](https://github.com/SecretFinance/SecretSwap/commit/cccfc8763537f48afe36c5ecc23e5f0daa7e48a4)
